Create docker for front-end
EdLinker/edlinker-frontend pull request #1
Opened 2021-02-18 11:35 UTC by RostyslavHavuka

2021-02-18 11:43 UTC, TArch64 requested changes

2021-02-18 11:43 UTC, TArch64 commented on .dockerignore
> +**/node_modules
У тебе можуть бути вкладені папки з нод модулями?

2021-02-18 11:43 UTC, TArch64 commented on Dockerfile.dev
> +FROM node:14
вказуй точну версію базового імеджа + старайся використовувати `alpine` сборку бо вона менше об'ємом

2021-02-18 11:43 UTC, TArch64 commented on Dockerfile.dev
> +RUN npm install -g @angular/cli @angular-devkit/build-angular && npm install
Тобі точно потрібні всі ці залежності глобально? Чому не використовуєш локальні?

2021-02-18 11:43 UTC, TArch64 commented on Dockerfile.dev
> +WORKDIR /home/dev/edlinker/edliker-front
доволі часто роблять просто `WORKDIR /app`

2021-02-18 11:43 UTC, TArch64 commented on Dockerfile.dev
> +EXPOSE 4200
експоус та стартову команду краще вказувати в `docker-compose.yml`, бо так це дає тобі
- можливість змінювати їх без ребілда імеджа
- вказувати різні взалежності від ситуації

2021-02-18 11:43 UTC, TArch64 commented on package.json
> +    "start": "ng serve --host=0.0.0.0 --port 4200",
така специфіка має вказуватися безпосередньо в докер конфігах. Людям на локалі воно не потрібно

2021-02-18 11:43 UTC, TArch64 commented on package.json
> +    "@angular-devkit/build-angular": "^0.1101.4",
Для чого тут змінював версію залежностей?

2021-02-18 11:43 UTC, TArch64 commented on docker-compose.yml
> +  angular:
назви це просто `frontend`. Абстрактність в назвах наше все

2021-02-18 11:43 UTC, TArch64 commented on package.json
> +    "start": "ng serve --host=0.0.0.0 --port 4200",
```yml
  command: npm run start -- --host=0.0.0.0
```
Порт 4200 завжди був і є дефолтним для ангуляра

2021-02-18 13:58 UTC, TArch64 requested changes

2021-02-18 13:58 UTC, TArch64 commented on Dockerfile.dev
> +WORKDIR /app
забув тут зробити інсталяцію нод модулів

2021-02-18 13:58 UTC, TArch64 commented on Dockerfile.dev
> +FROM node:14-alpine3.13
краще використай `14.15.5-alpine3.10`. Фіксована версія ноди наше все

2021-02-18 13:58 UTC, TArch64 commented on package-lock.json
> +      "version": "7.12.16",
а чому немає змін в package.json, а в package-lock.json є?

2021-02-18 13:59 UTC, TArch64 commented
а ти запускав апп? Він у тебе нормально відкривається? Зазвичай потрібно вказувати для девелопмента `--disable-host-check`

2021-02-18 14:41 UTC, RostyslavHavuka commented on Dockerfile.dev
> +WORKDIR /app
А для чого робиться інсталяція нод модулів у докер файлі?

2021-02-18 14:46 UTC, RostyslavHavuka commented
Так, я запускав і все парацює

2021-02-18 14:53 UTC, TArch64 commented on Dockerfile.dev
> +WORKDIR /app
Нод модулі змінюються не дуже часто тому вони в докерфайлі, бо інший варіант це руками запускати або кожен раз при запускові апу

2021-02-19 09:56 UTC, TArch64 commented on Dockerfile.dev
> +WORKDIR /app
встановлення workdir роби другим рядочком бо ця штука ніколи не буде змінюватися. Потім після цього роби копіювання package джейсонів, а після інсталяція модулів. Так у разі їх зміни докер скидав кеш і ставив заново модулі

2021-02-19 09:58 UTC, TArch64 commented on Dockerfile.dev
> +WORKDIR /app
ще можеш зробити отак
```Dockerfile
RUN npm install && /app/node_modules/.bin/ngcc
```

2021-02-19 09:59 UTC, TArch64 commented on Dockerfile.dev
> +WORKDIR /app
Тоді ще прибиреться компіляція ангуляровських модулів при кожному запуску проекта

2021-02-22 18:39 UTC, TArch64 approved these changes

2021-02-22 18:39 UTC, merged